[package]
name = "day09"
version = "0.9.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
libaoc.workspace = true
color-eyre.workspace = true
lending-iterator = "0.1.6"

[dev-dependencies]
indoc = "1.0.7"
pretty_assertions = "1.3.0"
rstest = "0.16.0"
