[package]
name = "day06"
version = "0.6.1"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
libaoc.workspace = true
color-eyre.workspace = true
itertools = "0.10.5"

[dev-dependencies]
pretty_assertions = "1.3.0"
rstest = "0.16.0"
