[package]
name = "day10"
version = "0.10.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
libaoc.workspace = true
color-eyre.workspace = true

[dev-dependencies]
indoc = "1.0.7"
pretty_assertions = "1.3.0"
rstest = "0.16.0"
